### ISSUE TITLE
Event payload does not respond to each

### ISSUE THREAD

**Issue by 2called-chaos** [kickstarter/rack-attack#100]
I noticed a large amount of exceptions in the form of

```
NoMethodError: undefined method `each' for #<Rack::Attack::Request:0x007f6eec788f90>
```

You can find the full trace here: https://gist.github.com/2called-chaos/b33da8599b16d8929ac5

You may notice that there is no rack attack in the trace and the gem which is causing the exception is appsignal by attempting to call `each` on the event payload.

The [rails documentation states](http://api.rubyonrails.org/classes/ActiveSupport/Notifications.html): "The payload is a mechanism that allows instrumenters to pass extra information to subscribers. Payloads consist of a hash whose contents are arbitrary and generally depend on the event."

Hackish fix proposal:
```ruby
  def each &block
    { request: self }.each(&block)
  end
```

**Comment by ktheory** [comment]
:wave: @2called-chaos,

I'm going to close this out. You're :100: percent right that I'm not following the spec, and that's a bug. :bug:

But it's a bug minimal  impact, since people are mostly writing original notification subscribers for rack-attack (I presume), with appsignal being an exception.

In fact, fixing the bug would probably cause more developer impact than leaving it as-is.

If anyone can think of a reasonable way to migrate towards hashes without breaking existing subscribers, I'd welcome a pull request.

And if this bug affects you, please chime in with an emoji. :smile:
