### ISSUE TITLE
Ability to add bantime for throttle

### ISSUE THREAD

**Issue by chrisjeon** [kickstarter/rack-attack#123]
Hello,

I was wondering if there was a way to add bantime for throttle method.  If not, what is the logic behind refresh rate for throttling?  For example, right now, we have set throttling for ip addresses and set a limit for 10 and period for 10 seconds.  It seems like the throttling works, but rack-attack allows the ip addresses through after a minute or so.  Is there a way to increase this time interval (for example, passing in additional parameters to the throttle method).  If not, what's the logic for setting the time interval between throttling?

**Comment by zmillman** [comment]
Throttling currently resets whenever a throttle period expires. You could set a longer period so that when the limit's exceeded, the IP is locked out for longer:

```ruby
# 60 requests/minute
throttle("req/ip", :limit => (10 * 60), :period => (10 * 60).seconds) do |req|
  req.ip
end
```

You might also try something like exponential backoff, which you can kind of do with Rack::Attack by layering multiple throttles: https://github.com/kickstarter/rack-attack/issues/106

**Comment by chrisjeon** [comment]
@zmillman, thanks for the help.  The exponential backoff seemed to work.  Thank you.
