### ISSUE TITLE
rack-attack get a wrong ip

### ISSUE THREAD

**Issue by koybe** [kickstarter/rack-attack#139]
i have deployed gitlab-7.11-stable on a redhat server in my company. one day all request to the website became 403 suddenly. After investigation, we found that is a protection of gitlab using rack-attack to keep gitlab health. this is awesome but one thing, we found that rack-attack get the wrong ip:

all the request is through nginx, nginx is deployed on the same server of gitlab
we visit gitlab through a domain like gitlab.xxx.local(eg.its ip is 1.2.3.4), and now,
not matter which user visit gitlab,if gitlab return 401 status and exceed the limit times, all request become 403 because gitlab or rack-attack has block the server which ip is 1.2.3.4, so it reject all the request.but this is wrong, it should get the user's real ip,not the nginx server's ip.

so, is this a bug of rack-attack or anything else i could do to solve the problem?

appreciate for any anwser!!

**Comment by ktheory** [comment]
I think it's a common misconfiguration in your web server. ☺️

You need to configure nginx to add an X-Forwarded-For header with the correct client IP address. Then rack's `req.ip` will return the value from the header, rather than your nginx server.

Add something like this in your nginx proxy config:

`proxy_set_header X-Forwarded-For $remote_addr;`

**Comment by Marks-Chan** [comment]
good job!it  works for me~

**Comment by koybe** [comment]
@ktheory thanks very much!!!

**Comment by sephethus** [comment]
> proxy_set_header X-Forwarded-For $remote_addr;

Anybody know where to set this in an already existing controller that was installed in a GCP cluster long before I got to this company?
