### ISSUE TITLE
Behind a load balancer

### ISSUE THREAD

**Issue by klawrence** [kickstarter/rack-attack#145]
I used the example throttle code

```
throttle('req/ip', limit: 100, period: 5.minutes) do |req|
  req.ip unless req.path.starts_with?('/assets')
end
```

This worked great on our staging server but immediately ran into the limit on production because req.ip returns the IP address of our load balancer and not the remote_ip of the client.

Note that remote_ip is a method in ActionDispatch::Request but not Rack::Attack::Request.

We are using Rails 3.2.2 on Ruby 2.2.2

I was able to workaround the problem with a new method on Rack::Attack::Request

```
class Rack::Attack
  class Request < ::Rack::Request
    def remote_ip
      @remote_ip ||= (env['action_dispatch.remote_ip'] || ip).to_s
    end
  end
end
```

and then

```
req.remote_ip unless req.path.starts_with?('/assets')
```

Maybe the README could suggest using remote_ip behind a load balancer?

**Comment by ktheory** [comment]
First off, I totally sympathize with you about how weird it is that Rails' `remote_ip` and Rack's `ip` method can return different things based on how your reverse proxy is set up.

It's bonkers. :stuck_out_tongue_closed_eyes:

Thanks for noting it here where searchers can find it.

IMHO, this is a bug for Rails and/or Rack to fix so that `ActionDispatch::Request#remote_ip` returns the same thing as `Rack::Request#ip`. I'd heartily :+1: that pull request.

**Comment by twk3** [comment]
@ktheory do you have a recommended approach for working around this? At the moment I'm planning to override rack request trusted_proxy? to use the same list I gave to action dispatch.

**Comment by ryanmaclean** [comment]
@ktheory is it maybe advisable to make note of this distinction somewhere?

**Comment by martyciz** [comment]
For Google App Engine env['action_dispatch.remote_ip'] still returned balancer IP, to get actual remote IP I added code like this:

```
def remote_ip
  remote = env['HTTP_X_FORWARDED_FOR'] ? env['HTTP_X_FORWARDED_FOR'].split(',')[0] : nil
  @remote_ip ||= (remote || ip).to_s
end
```

**Comment by arturopie** [comment]
@martyciz if you are using that `remote_ip` for some kind of whitelist/secure thing, that code is not secure since the client could 'spoof' `HTTP_X_FORWARDED_FOR` and set it to what ever ip they want?
You would want to use `env['HTTP_X_FORWARDED_FOR'].split(',')[-2]` instead depending on your proxy/load balancer configuration

**Comment by martyciz** [comment]
@arturopie can you further explain how client can 'spoof' `X-Forwarded-For` header?
Google App Engine load balancer [sets this header, here is the explanation of value](https://cloud.google.com/appengine/docs/flexible/ruby/reference/request-headers#request_headers):

> The first IP in this list is generally the IP of the client that created the request. The subsequent IPs provide information about proxy servers that also handled the request before it reached the application server

So my idea was to catch the first IP since that should be the client IP, do you suggest to instead focus on last visited proxy server (the last IP address in the header, not counting possible global forwarding rules)?

**Comment by arturopie** [comment]
As a hacker, I can set the header of the request to this:

X-Forwarded-For: 'a-fake-ip'

Then, the load balancer will append the real ip to the `X-Forwarded-For` because the header is already defined:

X-Forwarded-For: 'a-fake-ip, real-ip'

If there is no more proxies between the load balancer and the app (btw, nginx might be configured to add more to the header), then the app will receive the header content:

X-Forwarded-For: 'a-fake-ip, real-ip'

If you always take the first ip, now your app logs and any other feature you might have to use client ips will be using `a-fake-ip`.

The correct implementation is that, since you know how many proxies are between the client and the app, your app count from the last. For example, if you have just 1 proxy, you take the last ip. If you have 2 proxies, you take the second to last one. Also, not that this only works when only the proxies can access your app (e.g your app runs in a private subnet that only the load balancers can hit)

**Comment by jeromedalbert** [comment]
For people who are using Google Cloud Platform load balancing proxies, the user IP is only given inside the `HTTP_X_FORWARDED_FOR` header.

So Rack and Rails won't detect the user IP correctly. You could monkey-patch `Rack::Attack::Request` like suggested above, but that will fix the IP problem only for Rack::Attack. To fix the IP problem globally in my app, I monkey-patched both `Rack::Request` and `ActionDispatch::Request` to return the same IP values extracted from `HTTP_X_FORWARDED_FOR`.

If this can help anyone, here is what I did in a `config/initializers/request_ip.rb` Rails initializer:

```ruby
# Monkey patch request classes because the GCP Kubernetes proxy only
# gives us the user IP inside the HTTP_X_FORWARDED_FOR header.

module Rack
  class Request
    module Helpers
      alias_method :original_ip, :ip

      def ip
        # X-Forwarded-For format: <unverified IP(s)>, <immediate client IP>,
        # <global forwarding rule external IP>, <proxies running in GCP>
        #
        # If we are sure that we are running only 1 GCP proxy, and we have
        # no global forwarding rules, then we can get the second to last IP
        # as the immediate client IP.
        #
        # https://cloud.google.com/load-balancing/docs/https/#components
        forwarded_ips = split_ip_addresses(get_header('HTTP_X_FORWARDED_FOR'))
        forwarded_user_ip = forwarded_ips[-2]

        forwarded_user_ip || original_ip
      end
    end
  end
end

module ActionDispatch
  class Request
    def ip
      super
    end

    def remote_ip
      ip
    end
  end
end
```

**Comment by imajes** [comment]
a note about this.. it probably shouldn't assume the size of the forwarded_ips array. I'd look at how remote_ip works: https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/middleware/remote_ip.rb

**Comment by AdamFreemer** [comment]
I'm wondering if anyone has since tried any of the above to retrieve remote_ip. I recently installed rack-attack and get nil returned for request.remote_ip, request.ip, etc. Should I be able to fetch a client session ip with rack-attack or is it just considered not possible or something that will always be wonky?

**Comment by EmirVatric** [comment]
If somebody stumbles upon this issue, this is what ended up working for me.

```ruby
config.middleware.insert_after ActionDispatch::RemoteIp, Rack::Attack
config.action_dispatch.trusted_proxies = [IPAddr.new('ip')]

class Rack::Attack
  class Request < ::Rack::Request
    def remote_ip
      @remote_ip ||= ActionDispatch::Request.new(env).remote_ip
    end
  end
end
```

Now `req.remote_ip` should be correct.
