### ISSUE TITLE
throttle limit access by user in run-time

### ISSUE THREAD

**Issue by loingh** [kickstarter/rack-attack#397]
I have a question: I'd like to limit access api per user.

Example: User A can make 20 API calls per 30 minutes And user B can make 100 API calls per 5 hour in run-time. like so... How could i do that with rack-attack?

**Comment by lmansur** [comment]
What do you mean by throttling them in run-time?

You would like to change (and create) different throttling schemes while the server is running? Or just define the throttle regularly?

**Comment by lmansur** [comment]
You could make use of [proc limits and periods](https://github.com/kickstarter/rack-attack#throttlename-options-block) to accomplish this. Here is an example workflow:

Admin sets UserA to 100req/h (saves this info in the database)
UserA makes a request to your app
**Before** the request reaches `rack-attack`, you populate the request environment with the period and limit of UserA **[1]**
Request reaches `rack-attack`
`rack-attack` calls your limit and period procs to determine what their values are **[2]**
`rack-attack` throttles or not the request

**[1]:**
To do this, you will need to create a Rack Middleware and register it to be used **before** `rack-attack`. Your middleware will query the database to return the current_user and its throttle information (period and limit). It will then set this information in the `request.env`.

**[2]:**
The period and limit procs will ask `request.env` for their current values. This is the value you assigned previously in your custom middleware.

This approach means a database query in your middleware stack. You have to make sure this is OK for your app, since it will add some milliseconds to your response time.

I'm not sure this is the best approach, but it might work. Let me know if it does!

**Comment by loingh** [comment]
@lmansur can i use Rack::Attack.throttle(...) in Model, something like User Model?

**Comment by lmansur** [comment]
You can define a method using Rack::Attack anywhere, but the throttle must be registered (called) in an initializer file.
