### ISSUE TITLE
Throttling Graphql Requests

### ISSUE THREAD

**Issue by umer98** [kickstarter/rack-attack#401]
Hi,

I want to throttle specific GraphQL queries but since all GraphQL requests are made to the same endpoint, I'm not quite sure how to go about limiting requests for a specific set of queries. 

Could I do something in the resolver to manually increment the request counter for an IP? Any other ideas on how I could go about doing this?

Thanks,
Umer

**Comment by lmansur** [comment]
Hi @umer98.

Since `Rack::Attack` is designed to work within the Rack middleware stack, it doesn't expose a simple API for manually incrementing the counter.

However, it can be done. You'd have to access the list of registered throttles (`Rack::Attack.throttles`) and ask if it was `#matched_by?` the request, supplying it with an object that quacks like `Rack::Request` (or at the very least implements whatever `#matched_by?` requires).

Alternatively, since you are inside the resolver itself, you already know the request matched. So you can manually check and increment the counter by using `Rack::Attack.cache.count`, supplying it with the cache `key` and `period`.

Both options are wildly unstable and may break without notice.

With that said, you probably shouldn't be doing this. Since GraphQL requests can be as complex as the schema allows them to be, one GraphQL request can cost more than 100 "regular" requests. This means you will need to assign a cost to each query you defined and sum their costs against the actual request.

With such a complicated setup, you might be better off creating your own solution, since you would basically be using `rack-attack` as a throttle registry and cache adapter.

[Github's GraphQL API documentation](https://developer.github.com/v4/guides/resource-limitations/#rate-limit) might be an interesting read for your use case.

**Comment by grzuy** [comment]
Thank you @lmansur for you thorough response
