### ISSUE TITLE
Cache filling up hard drive

### ISSUE THREAD

**Issue by NoobSkie** [kickstarter/rack-attack#461]
When I am running rack attack on production after about a day or so I will get this error

`No space left on device@ rb_sysopen - /var/app/current/tmp/cache/.rack%3A%3Aattack%3A5249968%3Areq%2Fip%3A104.199.176.25320191129-1869-11sg00n`

I know i can fix it by redeploying but im looking for a more elgant solution

**Comment by grzuy** [comment]
Hi @NoobSkie,

Are you using `:file_store` in production?

**Comment by grzuy** [comment]
@NoobSkie Assuming you are, keep in mind the following extract from [Rails docs](https://guides.rubyonrails.org/caching_with_rails.html#activesupport-cache-filestore):

> [...] This cache store is appropriate for low to medium traffic sites that are served off one or two hosts. Server processes running on different hosts could share a cache by using a shared file system, but that setup is not recommended.

> **As the cache will grow until the disk is full, it is recommended to periodically clear out old entries**.

> This is the default cache store implementation (at "#{root}/tmp/cache/") if no explicit config.cache_store is supplied.

Hope it helps :-)

Closing for now, given this doesn't appear something outside the area or responsibility of this gem.

Let me know if you think otherwise.
