### ISSUE TITLE
NoMethodError: undefined method `increment' for nil:NilClass

### ISSUE THREAD

**Issue by nandosousafr** [kickstarter/rack-attack#71]
Hi everyone,

i'm getting this error in production using rack-attack.
![screen shot 2014-06-11 at 2 22 56 pm](https://cloud.githubusercontent.com/assets/818744/3248278/1fac5f7a-f18d-11e3-9303-d8a92e379d14.png)

see backtrace:
![screen shot 2014-06-11 at 2 24 10 pm](https://cloud.githubusercontent.com/assets/818744/3248293/4505a7f4-f18d-11e3-89db-b74e8b539250.png)

how to solve it?

**Comment by pisaacs** [comment]
Yes, misconfiguration as  @zmillman  suggested. For your `:dalli_store`, where do you specify the memcached server(s)?  The below setting would only be valid with memcached running on localhost on default port. 

```ruby
# config/enviroments/production.rb
config.cache_store = :dalli_store
```

To test memcached in production, try consoling (`rails c`) in production and running the below. 

```ruby
cache = ActiveSupport::Cache::MemCacheStore.new
cache.write('city', "Duckburgh")
cache.read('city')  
=> "Duckburgh"
```

@zmillman suggest closing unless we hear otherwise.
